#!/usr/bin/env node
'use strict'
const fs = require('fs'), path = require('path')

const PRE = 'masterpiece, best quality, absurdres, uncensored, flat color, afkArenaStyle, h4desstyle, ultrasharpdskStyle'
const SUF = 'simple background, cel shading, dark outlines, afkArenaStyle, h4desstyle, ultrasharpdskstyle'
const NEG = 'bad anatomy, bad hands, missing fingers, extra digits, fewer digits, cropped, worst quality, low quality, jpeg artifacts, signature, watermark, blurry, text, error, missing limb, floating limbs, disconnected limbs, malformed hands, long neck, mutated, ugly, deformed, (nsfw:1.3), realistic, photo, photography, 3d render'

// Template builders per archetype key
const T = {
  rhythm_rock: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, intense focused expression, powerful confident energy, ${d.mod}, band tee, ripped jeans, leather boots, studded belt, drumsticks tucked behind ear, leather wristbands, silver chains, ${d.kit}, drumsticks, behind drum kit, sticks raised mid-hit, power stance, ${SUF}`,
  rhythm_punk: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, snarling defiant expression, rebellious fierce energy, ${d.mod}, ripped fishnet shirt, leather jacket covered in patches, combat boots, torn tights, safety pins on jacket, spiked choker, multiple ear piercings, chain belt, ${d.kit}, drumsticks, standing behind kit, sticks raised in aggression, leaning forward, ${SUF}`,
  rhythm_grunge: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, detached melancholic expression, brooding distant gaze, ${d.mod}, oversized flannel shirt open over faded band tee, worn ripped jeans, old converse, worn leather bracelet, simple rings, old wristwatch, ${d.kit}, drumsticks, slouched behind kit, casual loose grip, head slightly bowed, ${SUF}`,
  rhythm_heavy_metal: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, fierce intense expression, commanding powerful energy, ${d.mod}, black band tee with logo, black skinny jeans, boots with buckles, leather vest with patches, spiked wristbands both arms, pentagram pendant, skull rings, black nail polish, ${d.kit}, drumsticks, explosive double-kick stance, hair flying, sticks blurred in motion, ${SUF}`,
  rhythm_funk: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, confident joyful expression, soulful groove energy, ${d.mod}, colorful wide-leg pants, vibrant crop top, platform shoes, chunky gold chains, large hoop earrings, stacked colorful bracelets, ${d.kit}, drumsticks, mid-groove head bob, sticks in fluid motion, pure pocket feel, ${SUF}`,
  rhythm_blues: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, soulful warm expression, emotionally present storytelling gaze, ${d.mod}, vintage suit jacket over collared shirt, suspenders, worn dress shoes, vintage pocket watch, simple gold ring, folded handkerchief, ${d.kit}, drumsticks, behind brush kit, gentle focused playing, head slightly tilted, ${SUF}`,
  rhythm_jazz: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, serene focused expression, intellectual composed energy, ${d.mod}, tailored blazer over silk blouse, high-waisted wide trousers, low heels, pearl stud earrings, delicate chain necklace, slim watch, ${d.kit}, drumsticks, behind minimal kit, brush held lightly, composed upright posture, ${SUF}`,
  rhythm_psychedelic: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, dreamy transcendent expression, eyes half closed in trance, ${d.mod}, flowing bohemian layers, tie-dye cosmic prints, sheer fabrics, crystal pendants, feather earrings, multiple rings, third eye bindhi gem, ${d.kit}, drumsticks, arms raised in trance-like playing, swaying, cosmic energy emanating, ${SUF}`,
  rhythm_prog_rock: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, intense calculating expression, focused mathematical precision, ${d.mod}, tailored dark asymmetric ensemble, architectural cut clothing, unusual geometric timepiece, minimal architectural jewelry, ${d.kit}, drumsticks, multi-limb coordination implied, complex kit surrounding her, ${SUF}`,
  melody_rock: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, passionate powerful expression, soaring emotional energy, ${d.mod}, worn leather jacket, vintage band tee, skinny jeans, ankle boots, guitar strap, pick necklace, silver rings, wristband, electric guitar, guitar strap over shoulder, guitar hero power stance, full body into the riff, ${SUF}`,
  melody_punk: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, aggressive sneering expression, raw defiant energy, ${d.mod}, DIY jacket covered in patches and pins, ripped tights, plaid skirt, boots, safety pins on jacket, studded belt, spiked bracelet, gauged ears, battered electric guitar covered in stickers, torn strap, aggressive forward lean, power chord stance, grimacing, ${SUF}`,
  melody_grunge: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, anguished raw expression, emotionally exposed vulnerability, ${d.mod}, oversized flannel over torn tee, ripped jeans, beat up boots, worn rubber bracelets, cheap rings, frayed friendship bracelet, beat up battered guitar, scratched body, old strap, hunched over guitar, lost in distortion, hair falling over face, ${SUF}`,
  melody_heavy_metal: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, fierce commanding expression, epic power energy, ${d.mod}, black leather jacket with studs, band tee, black jeans, heavy boots, spiked wristbands, skull pendant, rings on every finger, battle jacket, dark flying V or Explorer guitar, high drama instrument, dramatic shred pose, hair flying, guitar elevated, ${SUF}`,
  melody_funk: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, smooth confident expression, locked in the pocket energy, ${d.mod}, 70s inspired wide collar shirt, high-waist flares, platform shoes, chunky gold rings, layered gold chains, funky oversized glasses, sleek bass guitar, slap position implied, slap bass stance, body swaying, deeply in the groove, ${SUF}`,
  melody_blues: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, deeply soulful expression, emotional truthful storytelling, ${d.mod}, simple vintage dress or blouse, timeless classic style, slide ring on one finger, simple gold earrings, worn bracelet, acoustic guitar or clean electric, slide on finger, intimate connection with instrument, eyes closed feeling the notes, ${SUF}`,
  melody_jazz: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, sophisticated cool expression, fluid improvisational energy, ${d.mod}, elegant evening blazer, silk turtleneck, tailored wide trousers, pearl earrings, subtle gold necklace, elegant slim watch, tenor or alto saxophone, held with elegant confidence, saxophone raised, eyes closed, completely in the feel, ${SUF}`,
  melody_psychedelic: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, transcendent visionary expression, cosmic channeling energy, ${d.mod}, cosmic flowing robes with patterns, layered sheer fabrics, psychedelic prints, large crystal pendant, gem-encrusted rings, star hairpins, colorful keytar or cosmic synthesizer setup, arms spread across keys, head back, receiving cosmic transmission, ${SUF}`,
  melody_prog_rock: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, intense artistic vision, mathematical beauty in expression, ${d.mod}, theatrical asymmetric dark ensemble, dramatic architectural cut, unusual artistic statement jewelry, geometric pieces, violin bow raised or piano hands or saxophone, theatrical playing pose, drama and precision combined, ${SUF}`,
  vocals_rock: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, powerful commanding expression, passionate energy, ${d.mod}, leather pants, bold statement top, rock goddess stage outfit, boots, chunky silver jewelry, dramatic rings, layered necklaces, microphone on stand or handheld mic, commanding it, center stage power pose, mic in hand, owning every inch, ${SUF}`,
  vocals_punk: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, screaming raw expression, furious revolutionary energy, ${d.mod}, DIY punk jacket with patches, ripped clothes, fishnet, boots, chains everywhere, spiked collar, safety pins, multiple piercings, handheld mic ripped from stand, screaming into it, mic pulled aggressively, leaning into crowd, veins showing, ${SUF}`,
  vocals_grunge: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, anguished raw expression, emotionally exposed vulnerability, ${d.mod}, oversized vintage tee, flannel tied around waist, worn jeans, old shoes, minimal worn jewelry, old bracelet, microphone close, almost whispering or howling, hunched over mic, intimate pain made public, ${SUF}`,
  vocals_heavy_metal: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, fierce warrior expression, epic commanding power, ${d.mod}, armor-inspired black leather stage costume, dramatic details, epic statement necklace, warrior-inspired accessories, dark nail polish, mic clenched in fist, commanding the stage, arms spread wide, commanding the crowd, warrior goddess stance, ${SUF}`,
  vocals_funk: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, joyful magnetic expression, confident soulful energy, ${d.mod}, sequined or colorful stage outfit, 70s soul inspired, sparkle and soul, chunky gold jewelry, statement earrings, sequins, handheld mic, soulful smooth delivery, smooth dance move mid-song, effortlessly groovy, ${SUF}`,
  vocals_blues: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, deep sorrow and beauty combined, truthful emotional storytelling, ${d.mod}, vintage elegant dress, timeless classic beauty, period-appropriate, vintage pearl jewelry, long gloves perhaps, classic elegance, vintage microphone, intimate close connection, vintage intimate performer pose, close to mic, eyes closed, ${SUF}`,
  vocals_jazz: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, sultry sophisticated expression, intimate storytelling warmth, ${d.mod}, elegant jazz club gown or sophisticated tailored suit, pearl necklace, elegant drop earrings, satin gloves, elegant vintage microphone, leaning into it intimately, leaning into mic, one hand gesturing, eyes closed feeling the lyric, ${SUF}`,
  vocals_psychedelic: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, transcendent visionary expression, cosmic channeling, ${d.mod}, flowing cosmic robes, nature and cosmos inspired, sheer layers, large crystals, feather pieces, cosmic gem collection, arms open, voice as instrument, no mic or ethereal mic, arms open to cosmos, head back, receiving and transmitting, ${SUF}`,
  vocals_prog_rock: (d) => `${PRE}, 1girl, solo, ${d.hair}, ${d.color} hair, ${d.skin} skin, theatrical dramatic expression, epic storytelling intensity, ${d.mod}, theatrical dramatic stage costume, artistic and unusual, dramatic statement artistic pieces, theatrical dramatic microphone, operatic delivery, theatrical stage performance, dramatic gesture, operatic, ${SUF}`,
}

const ARCHETYPES = {
  rhythm_rock:'The Rock Drummer', rhythm_punk:'The Punk Drummer', rhythm_grunge:'The Grunge Drummer',
  rhythm_heavy_metal:'The Metal Drummer', rhythm_funk:'The Funk Drummer', rhythm_blues:'The Blues Drummer',
  rhythm_jazz:'The Jazz Drummer', rhythm_psychedelic:'The Psychedelic Drummer', rhythm_prog_rock:'The Prog Drummer',
  melody_rock:'The Rock Guitarist', melody_punk:'The Punk Guitarist', melody_grunge:'The Grunge Guitarist',
  melody_heavy_metal:'The Metal Shredder', melody_funk:'The Funk Bassist', melody_blues:'The Blues Slide Guitarist',
  melody_jazz:'The Jazz Saxophonist', melody_psychedelic:'The Psychedelic Keys Player', melody_prog_rock:'The Prog Multi-Instrumentalist',
  vocals_rock:'The Rock Vocalist', vocals_punk:'The Punk Screamer', vocals_grunge:'The Grunge Singer',
  vocals_heavy_metal:'The Metal Vocalist', vocals_funk:'The Funk Soul Singer', vocals_blues:'The Blues Singer',
  vocals_jazz:'The Jazz Vocalist', vocals_psychedelic:'The Psychedelic Voice', vocals_prog_rock:'The Prog Vocalist',
}

// Per-character data: [archetype_key, num, hair, color, skin, mod, kit_or_extra]
// mod = the variable modifier tokens that slot in after the archetype energy line
const CHARS = [
// ── RHYTHM ROCK (001-030) ─────────────────────────────────────────────────────
['rhythm_rock',1,'messy short hair','bleached blonde with dark roots','olive','groovy, solid','acoustic drums'],
['rhythm_rock',2,'sleek ponytail with flyaways','auburn','pale','groovy, solid','acoustic drums'],
['rhythm_rock',3,'sleek ponytail with flyaways','black','warm brown','tight, powerful','heavy acoustic'],
['rhythm_rock',4,'wild curly hair','dark brown','warm brown','raw, pounding','heavy acoustic'],
['rhythm_rock',5,'choppy layers','bleached blonde with dark roots','pale','groovy, solid','acoustic drums'],
['rhythm_rock',6,'wild curly hair','dark brown','tan','heavy, driving','heavy acoustic'],
['rhythm_rock',7,'wild curly hair','dark brown','warm brown','tight, powerful','acoustic drums'],
['rhythm_rock',8,'sleek ponytail with flyaways','bleached blonde with dark roots','olive','heavy, driving','acoustic drums'],
['rhythm_rock',9,'messy short hair','auburn','pale','tight, powerful','heavy acoustic'],
['rhythm_rock',10,'messy short hair','bleached blonde with dark roots','olive','tight, powerful','acoustic drums'],
['rhythm_rock',11,'sleek ponytail with flyaways','auburn','pale','raw, pounding','heavy acoustic'],
['rhythm_rock',12,'sleek ponytail with flyaways','black','warm brown','groovy, solid','acoustic drums'],
['rhythm_rock',13,'wild curly hair','dark brown','warm brown','groovy, solid','acoustic drums'],
['rhythm_rock',14,'choppy layers','bleached blonde with dark roots','pale','tight, powerful','heavy acoustic'],
['rhythm_rock',15,'wild curly hair','dark brown','tan','heavy, driving','acoustic drums'],
['rhythm_rock',16,'wild curly hair','dark brown','warm brown','tight, powerful','heavy acoustic'],
['rhythm_rock',17,'sleek ponytail with flyaways','bleached blonde with dark roots','olive','groovy, solid','heavy acoustic'],
['rhythm_rock',18,'messy short hair','auburn','pale','heavy, driving','heavy acoustic'],
['rhythm_rock',19,'wild curly hair','black','olive','raw, pounding','acoustic drums'],
['rhythm_rock',20,'sleek ponytail with flyaways','auburn','pale','tight, powerful','heavy acoustic'],
['rhythm_rock',21,'sleek ponytail with flyaways','black','warm brown','tight, powerful','heavy acoustic'],
['rhythm_rock',22,'wild curly hair','dark brown','warm brown','raw, pounding','heavy acoustic'],
['rhythm_rock',23,'choppy layers','bleached blonde with dark roots','pale','groovy, solid','acoustic drums'],
['rhythm_rock',24,'wild curly hair','dark brown','tan','tight, powerful','acoustic drums'],
['rhythm_rock',25,'wild curly hair','dark brown','warm brown','heavy, driving','acoustic drums'],
['rhythm_rock',26,'sleek ponytail with flyaways','bleached blonde with dark roots','olive','tight, powerful','heavy acoustic'],
['rhythm_rock',27,'messy short hair','auburn','pale','tight, powerful','heavy acoustic'],
['rhythm_rock',28,'wild curly hair','black','olive','tight, powerful','acoustic drums'],
['rhythm_rock',29,'wild curly hair','bleached blonde with dark roots','warm brown','raw, pounding','heavy acoustic'],
['rhythm_rock',30,'sleek ponytail with flyaways','black','warm brown','raw, pounding','acoustic drums'],
// ── RHYTHM PUNK (031-052) ─────────────────────────────────────────────────────
['rhythm_punk',31,'shaved sides long top','hot pink','pale','fast, aggressive','heavy acoustic'],
['rhythm_punk',32,'shaved sides long top','bleached white','fair','tight, explosive','acoustic drums'],
['rhythm_punk',33,'shaved sides long top','black and neon','pale','tight, explosive','acoustic drums'],
['rhythm_punk',34,'tall mohawk','hot pink','fair','tight, explosive','acoustic drums'],
['rhythm_punk',35,'half-shaved head','electric blue','pale','tight, explosive','acoustic drums'],
['rhythm_punk',36,'shaved sides long top','hot pink','pale','tight, explosive','acoustic drums'],
['rhythm_punk',37,'liberty spikes','electric blue','fair','relentless, chaotic','acoustic drums'],
['rhythm_punk',38,'half-shaved head','hot pink','fair','fast, aggressive','acoustic drums'],
['rhythm_punk',39,'half-shaved head','neon green','fair','fast, aggressive','acoustic drums'],
['rhythm_punk',40,'shaved sides long top','hot pink','pale','relentless, chaotic','acoustic drums'],
['rhythm_punk',41,'shaved sides long top','bleached white','fair','fast, aggressive','heavy acoustic'],
['rhythm_punk',42,'shaved sides long top','black and neon','pale','tight, explosive','heavy acoustic'],
['rhythm_punk',43,'tall mohawk','hot pink','fair','relentless, chaotic','acoustic drums'],
['rhythm_punk',44,'half-shaved head','electric blue','pale','relentless, chaotic','acoustic drums'],
['rhythm_punk',45,'shaved sides long top','hot pink','pale','fast, aggressive','acoustic drums'],
['rhythm_punk',46,'liberty spikes','electric blue','fair','relentless, chaotic','acoustic drums'],
['rhythm_punk',47,'half-shaved head','hot pink','fair','fast, aggressive','acoustic drums'],
['rhythm_punk',48,'half-shaved head','neon green','fair','relentless, chaotic','heavy acoustic'],
['rhythm_punk',49,'tall mohawk','hot pink','fair','fast, aggressive','heavy acoustic'],
['rhythm_punk',50,'shaved sides long top','bleached white','fair','fast, aggressive','heavy acoustic'],
['rhythm_punk',51,'shaved sides long top','black and neon','pale','tight, explosive','acoustic drums'],
['rhythm_punk',52,'tall mohawk','hot pink','fair','fast, aggressive','acoustic drums'],
// ── RHYTHM GRUNGE (053-070) ───────────────────────────────────────────────────
['rhythm_grunge',53,'tangled waves','faded black','fair','lazy, heavy','heavy acoustic'],
['rhythm_grunge',54,'tangled waves','faded black','fair','brooding, dark','acoustic drums'],
['rhythm_grunge',55,'long greasy hair','dark brown','pale sallow','brooding, dark','heavy acoustic'],
['rhythm_grunge',56,'tangled waves','dirty blonde','pale sallow','lazy, heavy','heavy acoustic'],
['rhythm_grunge',57,'wild unkempt curtains','faded black','fair','muddy, raw','heavy acoustic'],
['rhythm_grunge',58,'long greasy hair','dirty blonde','fair','muddy, raw','heavy acoustic'],
['rhythm_grunge',59,'tangled waves','faded black','pale sallow','brooding, dark','heavy acoustic'],
['rhythm_grunge',60,'tangled waves','dark brown','pale sallow','brooding, dark','heavy acoustic'],
['rhythm_grunge',61,'tangled waves','mousy brown','pale sallow','brooding, dark','heavy acoustic'],
['rhythm_grunge',62,'tangled waves','faded black','fair','brooding, dark','heavy acoustic'],
['rhythm_grunge',63,'tangled waves','faded black','fair','brooding, dark','acoustic drums'],
['rhythm_grunge',64,'long greasy hair','dark brown','pale sallow','lazy, heavy','heavy acoustic'],
['rhythm_grunge',65,'tangled waves','dirty blonde','pale sallow','brooding, dark','heavy acoustic'],
['rhythm_grunge',66,'wild unkempt curtains','faded black','fair','brooding, dark','heavy acoustic'],
['rhythm_grunge',67,'long greasy hair','dirty blonde','fair','lazy, heavy','heavy acoustic'],
['rhythm_grunge',68,'tangled waves','faded black','pale sallow','muddy, raw','heavy acoustic'],
['rhythm_grunge',69,'tangled waves','dirty blonde','pale sallow','brooding, dark','heavy acoustic'],
['rhythm_grunge',70,'tangled waves','mousy brown','pale sallow','brooding, dark','acoustic drums'],
// ── RHYTHM HEAVY METAL (071-085) ──────────────────────────────────────────────
['rhythm_heavy_metal',71,'thick dreadlocks','near-black dark brown','pale','machine-gun, relentless','heavy acoustic'],
['rhythm_heavy_metal',72,'thick dreadlocks','jet black','fair','machine-gun, relentless','heavy acoustic'],
['rhythm_heavy_metal',73,'wild headbanging hair mid-motion','dark blood red','olive','thunderous, precise','heavy acoustic'],
['rhythm_heavy_metal',74,'long straight hair flying','near-black dark brown','olive','epic, powerful','heavy acoustic'],
['rhythm_heavy_metal',75,'long straight hair flying','near-black dark brown','fair','epic, powerful','heavy acoustic'],
['rhythm_heavy_metal',76,'wild headbanging hair mid-motion','near-black dark brown','olive','thunderous, precise','heavy acoustic'],
['rhythm_heavy_metal',77,'thick dreadlocks','dark blood red','pale','thunderous, precise','acoustic drums'],
['rhythm_heavy_metal',78,'long straight hair flying','jet black','pale','thunderous, precise','heavy acoustic'],
['rhythm_heavy_metal',79,'wild headbanging hair mid-motion','near-black dark brown','pale','epic, powerful','heavy acoustic'],
['rhythm_heavy_metal',80,'thick dreadlocks','near-black dark brown','pale','thunderous, precise','acoustic drums'],
['rhythm_heavy_metal',81,'thick dreadlocks','jet black','fair','epic, powerful','heavy acoustic'],
['rhythm_heavy_metal',82,'wild headbanging hair mid-motion','dark blood red','olive','thunderous, precise','heavy acoustic'],
['rhythm_heavy_metal',83,'long straight hair flying','near-black dark brown','olive','epic, powerful','acoustic drums'],
['rhythm_heavy_metal',84,'long straight hair flying','near-black dark brown','fair','thunderous, precise','heavy acoustic'],
['rhythm_heavy_metal',85,'wild headbanging hair mid-motion','near-black dark brown','olive','machine-gun, relentless','acoustic drums'],
// ── RHYTHM FUNK (086-095) ─────────────────────────────────────────────────────
['rhythm_funk',86,'thick locs','natural black','rich dark','groovy, tight','acoustic drums'],
['rhythm_funk',87,'thick locs','dark brown','warm mahogany','groovy, tight','percussion ensemble'],
['rhythm_funk',88,'thick locs','rich brown with golden highlights','rich dark','syncopated, soulful','electronic drums'],
['rhythm_funk',89,'voluminous afro puffs','natural black','warm mahogany','syncopated, soulful','percussion ensemble'],
['rhythm_funk',90,'voluminous afro puffs','dark brown','rich dark','syncopated, soulful','acoustic drums'],
['rhythm_funk',91,'big natural curls','rich brown with golden highlights','deep brown','syncopated, soulful','electronic drums'],
['rhythm_funk',92,'voluminous afro puffs','rich brown with golden highlights','deep brown','syncopated, soulful','percussion ensemble'],
['rhythm_funk',93,'big natural curls','natural black','deep brown','funky, deep','acoustic drums'],
['rhythm_funk',94,'thick locs','dark brown','deep brown','groovy, tight','electronic drums'],
['rhythm_funk',95,'thick locs','natural black','rich dark','funky, deep','percussion ensemble'],
// ── RHYTHM BLUES (096-103) ────────────────────────────────────────────────────
['rhythm_blues',96,'finger waves','dark warm brown','rich dark','shuffling, warm','minimal kit'],
['rhythm_blues',97,'natural short curls','dark warm brown','deep ebony','shuffling, warm','acoustic drums'],
['rhythm_blues',98,'natural short curls','natural black','deep ebony','shuffling, warm','percussion ensemble'],
['rhythm_blues',99,'simple natural style','salt and pepper','deep ebony','deep, slow','percussion ensemble'],
['rhythm_blues',100,'finger waves','dark warm brown','rich dark','shuffling, warm','acoustic drums'],
['rhythm_blues',101,'natural short curls','salt and pepper','rich dark','deep, slow','percussion ensemble'],
['rhythm_blues',102,'natural short curls','dark warm brown','rich dark','deep, slow','acoustic drums'],
['rhythm_blues',103,'natural short curls','salt and pepper','warm brown','swinging, laid-back','percussion ensemble'],
// ── RHYTHM JAZZ (104-108) ─────────────────────────────────────────────────────
['rhythm_jazz',104,'short natural coils','deep dark brown','caramel','floating, light','acoustic drums'],
['rhythm_jazz',105,'short natural coils','glossy black','warm brown','subtle, complex','minimal kit'],
['rhythm_jazz',106,'elegant updo','glossy black','caramel','subtle, complex','percussion ensemble'],
['rhythm_jazz',107,'elegant updo','glossy black','caramel','delicate, swinging','minimal kit'],
['rhythm_jazz',108,'sleek sophisticated bob','glossy black','caramel','floating, light','percussion ensemble'],
// ── RHYTHM PSYCHEDELIC (109-110) ──────────────────────────────────────────────
['rhythm_psychedelic',109,'huge ethereal cloud of hair','deep violet','iridescent luminous','otherworldly, pulsing','electronic drums'],
['rhythm_psychedelic',110,'cosmic braids with gems','cosmic blue and purple','pale ethereal','otherworldly, pulsing','percussion ensemble'],
// ── RHYTHM PROG ROCK (111) ────────────────────────────────────────────────────
['rhythm_prog_rock',111,'precise architectural short cut','dark brown','olive','complex, shifting','minimal kit'],
// ── MELODY ROCK (001-030) ─────────────────────────────────────────────────────
['melody_rock',1,'wild tousled rock hair','platinum blonde','pale','melodic, emotional',''],
['melody_rock',2,'dramatic layered waves','jet black','tan','dark, heavy',''],
['melody_rock',3,'wild tousled rock hair','warm brown','olive','melodic, emotional',''],
['melody_rock',4,'volumious messy mane','jet black','pale','melodic, emotional',''],
['melody_rock',5,'volumious messy mane','platinum blonde','tan','melodic, emotional',''],
['melody_rock',6,'wild tousled rock hair','dark auburn red','pale','dark, heavy',''],
['melody_rock',7,'wild tousled rock hair','platinum blonde','tan','raw, energetic',''],
['melody_rock',8,'dramatic layered waves','platinum blonde','pale','melodic, emotional',''],
['melody_rock',9,'wild tousled rock hair','platinum blonde','olive','powerful, anthemic',''],
['melody_rock',10,'wild tousled rock hair','platinum blonde','pale','dark, heavy',''],
['melody_rock',11,'dramatic layered waves','jet black','tan','powerful, anthemic',''],
['melody_rock',12,'wild tousled rock hair','warm brown','olive','raw, energetic',''],
['melody_rock',13,'volumious messy mane','jet black','pale','raw, energetic',''],
['melody_rock',14,'volumious messy mane','platinum blonde','tan','powerful, anthemic',''],
['melody_rock',15,'wild tousled rock hair','dark auburn red','pale','powerful, anthemic',''],
['melody_rock',16,'wild tousled rock hair','platinum blonde','tan','raw, energetic',''],
['melody_rock',17,'dramatic layered waves','platinum blonde','pale','dark, heavy',''],
['melody_rock',18,'wild tousled rock hair','platinum blonde','olive','dark, heavy',''],
['melody_rock',19,'dramatic layered waves','jet black','tan','raw, energetic',''],
['melody_rock',20,'dramatic layered waves','jet black','tan','dark, heavy',''],
['melody_rock',21,'wild tousled rock hair','warm brown','olive','raw, energetic',''],
['melody_rock',22,'volumious messy mane','jet black','pale','powerful, anthemic',''],
['melody_rock',23,'volumious messy mane','platinum blonde','tan','raw, energetic',''],
['melody_rock',24,'wild tousled rock hair','dark auburn red','pale','powerful, anthemic',''],
['melody_rock',25,'wild tousled rock hair','platinum blonde','tan','powerful, anthemic',''],
['melody_rock',26,'dramatic layered waves','platinum blonde','pale','raw, energetic',''],
['melody_rock',27,'wild tousled rock hair','platinum blonde','olive','melodic, emotional',''],
['melody_rock',28,'dramatic layered waves','jet black','tan','melodic, emotional',''],
['melody_rock',29,'wild tousled rock hair','dark auburn red','pale','melodic, emotional',''],
['melody_rock',30,'wild tousled rock hair','warm brown','olive','melodic, emotional',''],
// ── MELODY PUNK (031-052) ─────────────────────────────────────────────────────
['melody_punk',31,'tall mohawk','bright orange','pale','rebellious, fast',''],
['melody_punk',32,'shaved sides with colorful top','black and white','pale','rebellious, fast',''],
['melody_punk',33,'shaved sides with colorful top','neon yellow','fair','rebellious, fast',''],
['melody_punk',34,'tall mohawk','electric red','fair','fierce, defiant',''],
['melody_punk',35,'shaved sides with colorful top','bright orange','pale','rebellious, fast',''],
['melody_punk',36,'liberty spikes','electric red','pale','rebellious, fast',''],
['melody_punk',37,'tall mohawk','electric red','fair','fierce, defiant',''],
['melody_punk',38,'liberty spikes','black and white','fair','fierce, defiant',''],
['melody_punk',39,'liberty spikes','neon yellow','fair','fierce, defiant',''],
['melody_punk',40,'tall mohawk','bright orange','pale','rebellious, fast',''],
['melody_punk',41,'shaved sides with colorful top','black and white','pale','fierce, defiant',''],
['melody_punk',42,'shaved sides with colorful top','neon yellow','fair','rebellious, fast',''],
['melody_punk',43,'tall mohawk','electric red','fair','rebellious, fast',''],
['melody_punk',44,'shaved sides with colorful top','bright orange','pale','rebellious, fast',''],
['melody_punk',45,'liberty spikes','electric red','pale','rebellious, fast',''],
['melody_punk',46,'tall mohawk','electric red','fair','angry, raw',''],
['melody_punk',47,'liberty spikes','black and white','fair','fierce, defiant',''],
['melody_punk',48,'liberty spikes','neon yellow','fair','angry, raw',''],
['melody_punk',49,'tall mohawk','neon yellow','pale','fierce, defiant',''],
['melody_punk',50,'shaved sides with colorful top','black and white','pale','angry, raw',''],
['melody_punk',51,'shaved sides with colorful top','neon yellow','fair','rebellious, fast',''],
['melody_punk',52,'tall mohawk','electric red','fair','angry, raw',''],
// ── MELODY GRUNGE (053-070) ───────────────────────────────────────────────────
['melody_grunge',53,'tangled waves','faded dark brown','fair','dark, brooding',''],
['melody_grunge',54,'messy curtain bangs','faded dark brown','fair','heavy, sludgy',''],
['melody_grunge',55,'tangled waves','faded dark brown','pale sallow','heavy, sludgy',''],
['melody_grunge',56,'messy curtain bangs','murky black','fair','heavy, sludgy',''],
['melody_grunge',57,'messy curtain bangs','murky black','pale sallow','raw, dirty',''],
['melody_grunge',58,'tangled waves','faded dark brown','fair','dark, brooding',''],
['melody_grunge',59,'messy curtain bangs','faded dark brown','fair','heavy, sludgy',''],
['melody_grunge',60,'tangled waves','faded dark brown','fair','raw, dirty',''],
['melody_grunge',61,'long unwashed disheveled hair','murky black','pale sallow','raw, dirty',''],
['melody_grunge',62,'tangled waves','faded dark brown','fair','raw, dirty',''],
['melody_grunge',63,'messy curtain bangs','faded dark brown','fair','raw, dirty',''],
['melody_grunge',64,'tangled waves','faded dark brown','pale sallow','dark, brooding',''],
['melody_grunge',65,'messy curtain bangs','murky black','fair','dark, brooding',''],
['melody_grunge',66,'messy curtain bangs','murky black','pale sallow','heavy, sludgy',''],
['melody_grunge',67,'tangled waves','faded dark brown','fair','raw, dirty',''],
['melody_grunge',68,'messy curtain bangs','faded dark brown','fair','heavy, sludgy',''],
['melody_grunge',69,'messy curtain bangs','faded dark brown','fair','dark, brooding',''],
['melody_grunge',70,'long unwashed disheveled hair','murky black','pale sallow','dark, brooding',''],
// ── MELODY HEAVY METAL (071-085) ──────────────────────────────────────────────
['melody_heavy_metal',71,'mid-headbang hair in motion','dark silver','pale','powerful, relentless',''],
['melody_heavy_metal',72,'mid-headbang hair in motion','dark silver','fair','dark, aggressive',''],
['melody_heavy_metal',73,'thick wild mane','dark silver','pale','powerful, relentless',''],
['melody_heavy_metal',74,'thick wild mane','dark silver','fair','brutal, epic',''],
['melody_heavy_metal',75,'thick wild mane','blood red highlights','fair','powerful, relentless',''],
['melody_heavy_metal',76,'mid-headbang hair in motion','dark silver','olive','powerful, relentless',''],
['melody_heavy_metal',77,'mid-headbang hair in motion','dark silver','fair','dark, aggressive',''],
['melody_heavy_metal',78,'long flowing dramatic hair','dark silver','pale','dark, aggressive',''],
['melody_heavy_metal',79,'thick wild mane','jet black','fair','dark, aggressive',''],
['melody_heavy_metal',80,'mid-headbang hair in motion','dark silver','pale','dark, aggressive',''],
['melody_heavy_metal',81,'mid-headbang hair in motion','dark silver','fair','dark, aggressive',''],
['melody_heavy_metal',82,'thick wild mane','dark silver','pale','powerful, relentless',''],
['melody_heavy_metal',83,'thick wild mane','dark silver','fair','powerful, relentless',''],
['melody_heavy_metal',84,'thick wild mane','blood red highlights','fair','powerful, relentless',''],
['melody_heavy_metal',85,'mid-headbang hair in motion','dark silver','olive','brutal, epic',''],
// ── MELODY FUNK (086-095) ─────────────────────────────────────────────────────
['melody_funk',86,'voluminous natural afro','warm dark brown','deep brown','groovy, smooth',''],
['melody_funk',87,'thick protective braids','rich brown with copper highlights','warm mahogany','groovy, smooth',''],
['melody_funk',88,'thick protective braids','rich brown with copper highlights','deep brown','groovy, smooth',''],
['melody_funk',89,'voluminous natural afro','rich brown with copper highlights','deep brown','bouncy, playful',''],
['melody_funk',90,'voluminous natural afro','rich brown with copper highlights','deep brown','groovy, smooth',''],
['melody_funk',91,'thick protective braids','rich brown with copper highlights','warm mahogany','bouncy, playful',''],
['melody_funk',92,'big natural puffs','natural black','warm mahogany','warm, deep',''],
['melody_funk',93,'thick protective braids','natural black','warm mahogany','groovy, smooth',''],
['melody_funk',94,'big natural puffs','natural black','warm mahogany','groovy, smooth',''],
['melody_funk',95,'voluminous natural afro','warm dark brown','deep brown','bouncy, playful',''],
// ── MELODY BLUES (096-103) ────────────────────────────────────────────────────
['melody_blues',96,'short practical natural','grey-streaked black','warm brown','deep, mournful',''],
['melody_blues',97,'natural simple style','warm dark brown','rich dark','warm, raw',''],
['melody_blues',98,'natural simple style','warm dark brown','rich dark','deep, mournful',''],
['melody_blues',99,'short practical natural','grey-streaked black','deep ebony','deep, mournful',''],
['melody_blues',100,'natural simple style','warm dark brown','warm brown','deep, mournful',''],
['melody_blues',101,'short practical natural','grey-streaked black','rich dark','soulful, emotional',''],
['melody_blues',102,'pinned back elegant','grey-streaked black','warm brown','deep, mournful',''],
['melody_blues',103,'pinned back elegant','grey-streaked black','deep ebony','warm, raw',''],
// ── MELODY JAZZ (104-108) ─────────────────────────────────────────────────────
['melody_jazz',104,'elegant vintage updo','glossy jet black','olive','sophisticated, smooth',''],
['melody_jazz',105,'sleek sophisticated bob','glossy jet black','olive','sophisticated, smooth',''],
['melody_jazz',106,'elegant vintage updo','deep dark brown','warm caramel','sophisticated, smooth',''],
['melody_jazz',107,'structured natural','glossy jet black','warm brown','complex, nuanced',''],
['melody_jazz',108,'sleek sophisticated bob','glossy jet black','olive','sophisticated, smooth',''],
// ── MELODY PSYCHEDELIC (109-110) ──────────────────────────────────────────────
['melody_psychedelic',109,'flowing decorated with gems and flowers','cosmic silver','pale ethereal','trippy, cosmic',''],
['melody_psychedelic',110,'flowing decorated with gems and flowers','iridescent rainbow','pale ethereal','ethereal, otherworldly',''],
// ── MELODY PROG ROCK (111) ────────────────────────────────────────────────────
['melody_prog_rock',111,'architectural precision cut','dark auburn','olive','cerebral, layered',''],
// ── VOCALS ROCK (001-030) ─────────────────────────────────────────────────────
['vocals_rock',1,'wild dramatic rock hair','dark auburn red','pale','energy, rebellion',''],
['vocals_rock',2,'voluminous tousled mane','platinum blonde','olive','energy, rebellion',''],
['vocals_rock',3,'wild dramatic rock hair','deep burgundy','pale','energy, rebellion',''],
['vocals_rock',4,'voluminous tousled mane','jet black','tan','energy, rebellion',''],
['vocals_rock',5,'wild dramatic rock hair','platinum blonde','olive','passion, power',''],
['vocals_rock',6,'wild dramatic rock hair','dark auburn red','pale','energy, rebellion',''],
['vocals_rock',7,'voluminous tousled mane','platinum blonde','pale','hope, defiance',''],
['vocals_rock',8,'wild dramatic rock hair','dark auburn red','pale','passion, power',''],
['vocals_rock',9,'wild dramatic rock hair','deep burgundy','tan','passion, power',''],
['vocals_rock',10,'wild dramatic rock hair','dark auburn red','pale','energy, rebellion',''],
['vocals_rock',11,'voluminous tousled mane','platinum blonde','olive','energy, rebellion',''],
['vocals_rock',12,'wild dramatic rock hair','deep burgundy','pale','passion, power',''],
['vocals_rock',13,'voluminous tousled mane','jet black','tan','hope, defiance',''],
['vocals_rock',14,'wild dramatic rock hair','platinum blonde','olive','passion, power',''],
['vocals_rock',15,'wild dramatic rock hair','dark auburn red','pale','hope, defiance',''],
['vocals_rock',16,'voluminous tousled mane','platinum blonde','pale','passion, power',''],
['vocals_rock',17,'wild dramatic rock hair','dark auburn red','pale','energy, rebellion',''],
['vocals_rock',18,'wild dramatic rock hair','deep burgundy','tan','hope, defiance',''],
['vocals_rock',19,'voluminous tousled mane','deep burgundy','pale','energy, rebellion',''],
['vocals_rock',20,'voluminous tousled mane','platinum blonde','olive','hope, defiance',''],
['vocals_rock',21,'wild dramatic rock hair','deep burgundy','pale','passion, power',''],
['vocals_rock',22,'voluminous tousled mane','jet black','tan','hope, defiance',''],
['vocals_rock',23,'wild dramatic rock hair','platinum blonde','olive','energy, rebellion',''],
['vocals_rock',24,'wild dramatic rock hair','dark auburn red','pale','passion, power',''],
['vocals_rock',25,'voluminous tousled mane','platinum blonde','pale','passion, power',''],
['vocals_rock',26,'wild dramatic rock hair','dark auburn red','pale','energy, rebellion',''],
['vocals_rock',27,'wild dramatic rock hair','deep burgundy','tan','passion, power',''],
['vocals_rock',28,'voluminous tousled mane','deep burgundy','pale','energy, rebellion',''],
['vocals_rock',29,'wild dramatic rock hair','deep burgundy','olive','energy, rebellion',''],
['vocals_rock',30,'wild dramatic rock hair','deep burgundy','pale','hope, defiance',''],
// ── VOCALS PUNK (031-052) ─────────────────────────────────────────────────────
['vocals_punk',31,'half-shaved','hot pink','fair','anger, defiance',''],
['vocals_punk',32,'mohawk','acid green','pale','urgency, frustration',''],
['vocals_punk',33,'mohawk','neon orange','pale','anger, defiance',''],
['vocals_punk',34,'shaved with colorful top','acid green','pale','rage, rebellion',''],
['vocals_punk',35,'shaved with colorful top','hot pink','fair','urgency, frustration',''],
['vocals_punk',36,'liberty spikes','electric blue','fair','anger, defiance',''],
['vocals_punk',37,'half-shaved','neon orange','pale','urgency, frustration',''],
['vocals_punk',38,'liberty spikes','electric blue','fair','urgency, frustration',''],
['vocals_punk',39,'liberty spikes','electric blue','fair','urgency, frustration',''],
['vocals_punk',40,'half-shaved','hot pink','fair','urgency, frustration',''],
['vocals_punk',41,'mohawk','acid green','pale','urgency, frustration',''],
['vocals_punk',42,'mohawk','neon orange','pale','rage, rebellion',''],
['vocals_punk',43,'shaved with colorful top','acid green','pale','anger, defiance',''],
['vocals_punk',44,'shaved with colorful top','hot pink','fair','anger, defiance',''],
['vocals_punk',45,'liberty spikes','electric blue','fair','anger, defiance',''],
['vocals_punk',46,'half-shaved','neon orange','pale','urgency, frustration',''],
['vocals_punk',47,'liberty spikes','electric blue','fair','anger, defiance',''],
['vocals_punk',48,'liberty spikes','electric blue','fair','urgency, frustration',''],
['vocals_punk',49,'shaved with colorful top','neon orange','pale','anger, defiance',''],
['vocals_punk',50,'mohawk','acid green','pale','rage, rebellion',''],
['vocals_punk',51,'mohawk','neon orange','pale','anger, defiance',''],
['vocals_punk',52,'shaved with colorful top','acid green','pale','anger, defiance',''],
// ── VOCALS GRUNGE (053-070) ───────────────────────────────────────────────────
['vocals_grunge',53,'tangled waves over face','washed out black','fair sallow','despair, apathy',''],
['vocals_grunge',54,'long messy unwashed hair','washed out black','pale','despair, apathy',''],
['vocals_grunge',55,'tangled waves over face','washed out black','fair sallow','despair, apathy',''],
['vocals_grunge',56,'tangled waves over face','faded brown','fair sallow','isolation, angst',''],
['vocals_grunge',57,'tangled waves over face','dirty blonde','pale','numbness, frustration',''],
['vocals_grunge',58,'tangled waves over face','washed out black','fair sallow','isolation, angst',''],
['vocals_grunge',59,'tangled waves over face','washed out black','pale','despair, apathy',''],
['vocals_grunge',60,'long messy unwashed hair','faded brown','pale','despair, apathy',''],
['vocals_grunge',61,'tangled waves over face','dirty blonde','pale','despair, apathy',''],
['vocals_grunge',62,'tangled waves over face','washed out black','fair sallow','numbness, frustration',''],
['vocals_grunge',63,'long messy unwashed hair','washed out black','pale','numbness, frustration',''],
['vocals_grunge',64,'tangled waves over face','washed out black','fair sallow','numbness, frustration',''],
['vocals_grunge',65,'tangled waves over face','faded brown','fair sallow','despair, apathy',''],
['vocals_grunge',66,'tangled waves over face','dirty blonde','pale','despair, apathy',''],
['vocals_grunge',67,'tangled waves over face','washed out black','fair sallow','despair, apathy',''],
['vocals_grunge',68,'tangled waves over face','washed out black','pale','despair, apathy',''],
['vocals_grunge',69,'tangled waves over face','washed out black','fair sallow','isolation, angst',''],
['vocals_grunge',70,'tangled waves over face','dirty blonde','pale','numbness, frustration',''],
// ── VOCALS HEAVY METAL (071-085) ──────────────────────────────────────────────
['vocals_heavy_metal',71,'epic mane mid-motion','blood red','olive','fury, defiance',''],
['vocals_heavy_metal',72,'epic mane mid-motion','blood red','olive','fury, defiance',''],
['vocals_heavy_metal',73,'epic mane mid-motion','dark silver grey','pale','fury, defiance',''],
['vocals_heavy_metal',74,'epic mane mid-motion','dark silver grey','fair','fury, defiance',''],
['vocals_heavy_metal',75,'long dramatic flowing hair','dark silver grey','fair','rage, power',''],
['vocals_heavy_metal',76,'epic mane mid-motion','blood red','fair','fury, defiance',''],
['vocals_heavy_metal',77,'epic mane mid-motion','blood red','olive','fury, defiance',''],
['vocals_heavy_metal',78,'epic mane mid-motion','dark silver grey','olive','epic, conquest',''],
['vocals_heavy_metal',79,'epic mane mid-motion','dark silver grey','fair','epic, conquest',''],
['vocals_heavy_metal',80,'epic mane mid-motion','blood red','olive','rage, power',''],
['vocals_heavy_metal',81,'epic mane mid-motion','blood red','olive','epic, conquest',''],
['vocals_heavy_metal',82,'epic mane mid-motion','dark silver grey','pale','epic, conquest',''],
['vocals_heavy_metal',83,'epic mane mid-motion','dark silver grey','fair','rage, power',''],
['vocals_heavy_metal',84,'long dramatic flowing hair','dark silver grey','fair','rage, power',''],
['vocals_heavy_metal',85,'epic mane mid-motion','blood red','fair','epic, conquest',''],
// ── VOCALS FUNK (086-095) ─────────────────────────────────────────────────────
['vocals_funk',86,'voluminous braids','natural black','warm mahogany','joy, confidence',''],
['vocals_funk',87,'gorgeous natural puffs','natural black','warm mahogany','celebration, sensuality',''],
['vocals_funk',88,'big natural afro','warm dark brown','deep brown','joy, confidence',''],
['vocals_funk',89,'voluminous braids','rich brown gold','warm mahogany','joy, confidence',''],
['vocals_funk',90,'big natural afro','natural black','warm mahogany','playfulness, soul',''],
['vocals_funk',91,'gorgeous natural puffs','rich brown gold','rich dark','joy, confidence',''],
['vocals_funk',92,'big natural afro','rich brown gold','deep brown','joy, confidence',''],
['vocals_funk',93,'voluminous braids','rich brown gold','rich dark','playfulness, soul',''],
['vocals_funk',94,'gorgeous natural puffs','natural black','warm mahogany','joy, confidence',''],
['vocals_funk',95,'voluminous braids','natural black','warm mahogany','playfulness, soul',''],
// ── VOCALS BLUES (096-103) ────────────────────────────────────────────────────
['vocals_blues',96,'vintage elegant finger waves','salt and pepper','deep ebony','pain, resilience',''],
['vocals_blues',97,'classic pinned style','warm dark brown','deep ebony','pain, resilience',''],
['vocals_blues',98,'classic pinned style','warm dark brown','warm brown','pain, resilience',''],
['vocals_blues',99,'vintage elegant finger waves','salt and pepper','rich dark','loss, hope',''],
['vocals_blues',100,'natural simple','natural black','rich dark','sorrow, longing',''],
['vocals_blues',101,'vintage elegant finger waves','salt and pepper','rich dark','pain, resilience',''],
['vocals_blues',102,'vintage elegant finger waves','salt and pepper','warm brown','sorrow, longing',''],
['vocals_blues',103,'classic pinned style','warm dark brown','rich dark','loss, hope',''],
// ── VOCALS JAZZ (104-108) ─────────────────────────────────────────────────────
['vocals_jazz',104,'classic finger waves','deep warm brown','warm caramel','nostalgia, desire',''],
['vocals_jazz',105,'sleek vintage updo','deep warm brown','warm caramel','melancholy, beauty',''],
['vocals_jazz',106,'sleek vintage updo','glossy jet black','olive','longing, sophistication',''],
['vocals_jazz',107,'classic finger waves','glossy jet black','olive','longing, sophistication',''],
['vocals_jazz',108,'sleek vintage updo','deep warm brown','warm caramel','longing, sophistication',''],
// ── VOCALS PSYCHEDELIC (109-110) ──────────────────────────────────────────────
['vocals_psychedelic',109,'adorned with flowers and crystals','cosmic silver blue','luminous otherworldly','wonder, transcendence',''],
['vocals_psychedelic',110,'enormous flowing cosmic hair','cosmic silver blue','pale ethereal','cosmic, dissolution',''],
// ── VOCALS PROG ROCK (111) ────────────────────────────────────────────────────
['vocals_prog_rock',111,'dramatic theatrical style','deep auburn','olive','awe, complexity',''],
]

// Character names from art_prompts.md
const NAMES = {
'rhythm_rock_001':'Gale Throne','rhythm_rock_002':'Kira Heart','rhythm_rock_003':'Sage Breaker','rhythm_rock_004':'Sage Anvil','rhythm_rock_005':'Wraith Halo','rhythm_rock_006':'Hollow Fire','rhythm_rock_007':'Ember Quake','rhythm_rock_008':'Thorn Wolf','rhythm_rock_009':'Jinx Wind','rhythm_rock_010':'Vesper Maelstrom','rhythm_rock_011':'Glitch Splinter','rhythm_rock_012':'Zephyr Surge','rhythm_rock_013':'Jolt Singer','rhythm_rock_014':'Drift Howler','rhythm_rock_015':'Lark Dancer','rhythm_rock_016':'Umbra Shadow','rhythm_rock_017':'Myth Dirge','rhythm_rock_018':'Xerxa Glyph','rhythm_rock_019':'Ursa Cobra','rhythm_rock_020':'Indigo Bloom','rhythm_rock_021':'Siren Glyph','rhythm_rock_022':'Arc Mystic','rhythm_rock_023':'Reverie Hymn','rhythm_rock_024':'Ghost Slayer','rhythm_rock_025':'Cyan Specter','rhythm_rock_026':'Twilight Whisper','rhythm_rock_027':'Prism Eclipse','rhythm_rock_028':'Kira Keeper','rhythm_rock_029':'Chrome Frost','rhythm_rock_030':'Juno Arrow',
'rhythm_punk_031':'Umber Prophet','rhythm_punk_032':'Fury Raven','rhythm_punk_033':'Pandora Hymn','rhythm_punk_034':'Storm Spark','rhythm_punk_035':'Zephyr Fist','rhythm_punk_036':'Twilight Fracture','rhythm_punk_037':'Moss Nadir','rhythm_punk_038':'Xerxa Bloom','rhythm_punk_039':'Selene Shield','rhythm_punk_040':'Gale Arrow','rhythm_punk_041':'Sage Panther','rhythm_punk_042':'Karma Jaguar','rhythm_punk_043':'Reverie Slayer','rhythm_punk_044':'Opal Fire','rhythm_punk_045':'Umbra Keeper','rhythm_punk_046':'Knell Howler','rhythm_punk_047':'Silken Oracle','rhythm_punk_048':'Tempest Fury','rhythm_punk_049':'Solstice Weaver','rhythm_punk_050':'Catalyst Maelstrom','rhythm_punk_051':'Lyra Zenith','rhythm_punk_052':'Glitch Dawn',
'rhythm_grunge_053':'Ghost Breaker','rhythm_grunge_054':'Nova Shadow','rhythm_grunge_055':'Selene Hunter','rhythm_grunge_056':'Cyan Weaver','rhythm_grunge_057':'Draven Spire','rhythm_grunge_058':'Inferno Maelstrom','rhythm_grunge_059':'Willow Mystic','rhythm_grunge_060':'Cinder Requiem','rhythm_grunge_061':'Vesper Walker','rhythm_grunge_062':'Knell Anvil','rhythm_grunge_063':'Rubix Maelstrom','rhythm_grunge_064':'Raven Hunter','rhythm_grunge_065':'Enigma Phoenix','rhythm_grunge_066':'Zenith Scythe','rhythm_grunge_067':'Quartz Gauntlet','rhythm_grunge_068':'Omega Roar','rhythm_grunge_069':'Mirage Scythe','rhythm_grunge_070':'Omega Maelstrom',
'rhythm_heavy_metal_071':'Xyla Shield','rhythm_heavy_metal_072':'Mercury Wolf','rhythm_heavy_metal_073':'Athena Rune','rhythm_heavy_metal_074':'Reign Star','rhythm_heavy_metal_075':'Silken Prophet','rhythm_heavy_metal_076':'Nyx Whisper','rhythm_heavy_metal_077':'Xerxa Raven','rhythm_heavy_metal_078':'Volt Spark','rhythm_heavy_metal_079':'Fern Keeper','rhythm_heavy_metal_080':'Twilight Wyvern','rhythm_heavy_metal_081':'Drift Ember','rhythm_heavy_metal_082':'Zenith Maiden','rhythm_heavy_metal_083':'Obsidian Shade','rhythm_heavy_metal_084':'Gale Ember','rhythm_heavy_metal_085':'Helix Spark',
'rhythm_funk_086':'Fury Crown','rhythm_funk_087':'Karma Raven','rhythm_funk_088':'Nimbus Vine','rhythm_funk_089':'Prism Panther','rhythm_funk_090':'Apex Prophet','rhythm_funk_091':'Yuki Wave','rhythm_funk_092':'Tempest Nadir','rhythm_funk_093':'Pyre Fracture','rhythm_funk_094':'Jinx Tremor','rhythm_funk_095':'Feral Mask',
'rhythm_blues_096':'Iron Star','rhythm_blues_097':'Mirage Shield','rhythm_blues_098':'Orbit Dusk','rhythm_blues_099':'Kira Dagger','rhythm_blues_100':'Hex Key','rhythm_blues_101':'Inferno Whisper','rhythm_blues_102':'Umber Crown','rhythm_blues_103':'Bolt Dusk',
'rhythm_jazz_104':'Myst Pulse','rhythm_jazz_105':'Phantom Dawn','rhythm_jazz_106':'Wren Weaver','rhythm_jazz_107':'Rift Singer','rhythm_jazz_108':'Cyan Eye',
'rhythm_psychedelic_109':'Solstice Mask','rhythm_psychedelic_110':'Luna Shrike',
'rhythm_prog_rock_111':'Rowan Specter',
'melody_rock_001':'Volt Wail','melody_rock_002':'Lyra Sigil','melody_rock_003':'Astra Halo','melody_rock_004':'Havoc Shadow','melody_rock_005':'Fern Slayer','melody_rock_006':'Sorrow Vine','melody_rock_007':'Luna Rapier','melody_rock_008':'Bolt Maelstrom','melody_rock_009':'Mira Valkyrie','melody_rock_010':'Crimson Echo','melody_rock_011':'Quartz Flame','melody_rock_012':'Myst Roar','melody_rock_013':'Arc Roar','melody_rock_014':'Juno Key','melody_rock_015':'Blight Rider','melody_rock_016':'Zero Quake','melody_rock_017':'Ursa Heart','melody_rock_018':'Sorrow Phoenix','melody_rock_019':'Cinder Aria','melody_rock_020':'Blaze Flame','melody_rock_021':'Pulse Sigil','melody_rock_022':'Blaze Fracture','melody_rock_023':'Iron Key','melody_rock_024':'Kismet Flame','melody_rock_025':'Sorrow Falcon','melody_rock_026':'Willow Stone','melody_rock_027':'Athena Wind','melody_rock_028':'Trix Shade','melody_rock_029':'Hollow Heart','melody_rock_030':'Spectra Bringer',
'melody_punk_031':'Draven Phoenix','melody_punk_032':'Reign Lynx','melody_punk_033':'Myst Serpent','melody_punk_034':'Athena Whisper','melody_punk_035':'Garnet Sigil','melody_punk_036':'Catalyst Raven','melody_punk_037':'Rubix Glyph','melody_punk_038':'Athena Spire','melody_punk_039':'Indigo Shade','melody_punk_040':'Xerxa Oracle','melody_punk_041':'Athena Keeper','melody_punk_042':'Quartz Vine','melody_punk_043':'Glitch Fang','melody_punk_044':'Quill Cobra','melody_punk_045':'Nova Fist','melody_punk_046':'Lux Prism','melody_punk_047':'Pixel Surge','melody_punk_048':'Mira Spark','melody_punk_049':'Lyric Anvil','melody_punk_050':'Nimbus Fire','melody_punk_051':'Catalyst Singer','melody_punk_052':'Ash Spire',
'melody_grunge_053':'Glitch Hymn','melody_grunge_054':'Echo Shade','melody_grunge_055':'Kira Ember','melody_grunge_056':'Nebula Wave','melody_grunge_057':'Knell Wraith','melody_grunge_058':'Nyx Crown','melody_grunge_059':'Iron Moon','melody_grunge_060':'Volt Wolf','melody_grunge_061':'Quantum Flare','melody_grunge_062':'Jinx Hunter','melody_grunge_063':'Phantom Cinder','melody_grunge_064':'Blight Oracle','melody_grunge_065':'Nova Shield','melody_grunge_066':'Rowan Rune','melody_grunge_067':'Nyx Fire','melody_grunge_068':'Fern Splinter','melody_grunge_069':'Fern Viper','melody_grunge_070':'Velvet Mask',
'melody_heavy_metal_071':'Echo Wind','melody_heavy_metal_072':'Zenith Cinder','melody_heavy_metal_073':'Xen Requiem','melody_heavy_metal_074':'Wisp Cipher','melody_heavy_metal_075':'Andromeda Frost','melody_heavy_metal_076':'Shade Apex','melody_heavy_metal_077':'Selene Jaguar','melody_heavy_metal_078':'Athena Walker','melody_heavy_metal_079':'Myth Dagger','melody_heavy_metal_080':'Haze Tremor','melody_heavy_metal_081':'Sorrow Shade','melody_heavy_metal_082':'Rowan Nadir','melody_heavy_metal_083':'Umbra Wolf','melody_heavy_metal_084':'Wraith Cinder','melody_heavy_metal_085':'Velvet Requiem',
'melody_funk_086':'Iris Throne','melody_funk_087':'Zenith Seeker','melody_funk_088':'Helix Rune','melody_funk_089':'Myst Fury','melody_funk_090':'Hollow Phoenix','melody_funk_091':'Banshee Fist','melody_funk_092':'Catalyst Scythe','melody_funk_093':'Astra Hammer','melody_funk_094':'Spectra Ember','melody_funk_095':'Silken Lynx',
'melody_blues_096':'Ivy Valkyrie','melody_blues_097':'Briar Nexus','melody_blues_098':'Xyla Flame','melody_blues_099':'Astra Keeper','melody_blues_100':'Blade Quake','melody_blues_101':'Pixel Hawk','melody_blues_102':'Arc Wolf','melody_blues_103':'Reverie Ember',
'melody_jazz_104':'Reign Quake','melody_jazz_105':'Coral Mystic','melody_jazz_106':'Sorrow Wind','melody_jazz_107':'Fractal Viper','melody_jazz_108':'Tsunami Lynx',
'melody_psychedelic_109':'Chrome Fang','melody_psychedelic_110':'Terra Singer',
'melody_prog_rock_111':'Pyre Vine',
'vocals_rock_001':'Mercury Muse','vocals_rock_002':'Raven Prism','vocals_rock_003':'Rift Veil','vocals_rock_004':'Kismet Howler','vocals_rock_005':'Electra Breaker','vocals_rock_006':'Sage Jaguar','vocals_rock_007':'Spectra Phantom','vocals_rock_008':'Neon Soul','vocals_rock_009':'Kestrel Muse','vocals_rock_010':'Knell Phantom','vocals_rock_011':'Shade Chain','vocals_rock_012':'Shade Gate','vocals_rock_013':'Banshee Bringer','vocals_rock_014':'Iron Breaker','vocals_rock_015':'Axiom Dagger','vocals_rock_016':'Lithium Lynx','vocals_rock_017':'Onyx Rider','vocals_rock_018':'Trix Falcon','vocals_rock_019':'Onyx Star','vocals_rock_020':'Jet Zenith','vocals_rock_021':'Artemis Requiem','vocals_rock_022':'Phantom Dirge','vocals_rock_023':'Coral Dusk','vocals_rock_024':'Zero Roar','vocals_rock_025':'Kestrel Prophet','vocals_rock_026':'Grim Shrike','vocals_rock_027':'Draven Glyph','vocals_rock_028':'Tsunami Pulse','vocals_rock_029':'Ghost Soul','vocals_rock_030':'Havoc Jaguar',
'vocals_punk_031':'Arc Key','vocals_punk_032':'Myst Tower','vocals_punk_033':'Lithium Phantom','vocals_punk_034':'Storm Siren','vocals_punk_035':'Blade Gate','vocals_punk_036':'Cassiopeia Heart','vocals_punk_037':'Inferno Tremor','vocals_punk_038':'Raven Splinter','vocals_punk_039':'Moss Valkyrie','vocals_punk_040':'Kismet Singer','vocals_punk_041':'Dawn Mantra','vocals_punk_042':'Gale Falcon','vocals_punk_043':'Blight Viper','vocals_punk_044':'Lux Vortex','vocals_punk_045':'Reign Rider','vocals_punk_046':'Drift Dancer','vocals_punk_047':'Quantum Slayer','vocals_punk_048':'Coral Hammer','vocals_punk_049':'Umbra Rider','vocals_punk_050':'Noir Shield','vocals_punk_051':'Echo Falcon','vocals_punk_052':'Flux Nadir',
'vocals_grunge_053':'Wisp Vine','vocals_grunge_054':'Yuki Shield','vocals_grunge_055':'Yuki Moon','vocals_grunge_056':'Mira Crown','vocals_grunge_057':'Coral Gate','vocals_grunge_058':'Reign Panther','vocals_grunge_059':'Quantum Key','vocals_grunge_060':'Kira Shriek','vocals_grunge_061':'Eve Surge','vocals_grunge_062':'Lux Forge','vocals_grunge_063':'Iris Queen','vocals_grunge_064':'Lithium Dagger','vocals_grunge_065':'Void Rider','vocals_grunge_066':'Siren Scythe','vocals_grunge_067':'Ash Fracture','vocals_grunge_068':'Electra Flare','vocals_grunge_069':'Quartz Nexus','vocals_grunge_070':'Warp Lament',
'vocals_heavy_metal_071':'Jade Fury','vocals_heavy_metal_072':'Raven Crown','vocals_heavy_metal_073':'Blaze Anvil','vocals_heavy_metal_074':'Sorrow Hymn','vocals_heavy_metal_075':'Dawn Wind','vocals_heavy_metal_076':'Banshee Crown','vocals_heavy_metal_077':'Drift Lynx','vocals_heavy_metal_078':'Drift Scythe','vocals_heavy_metal_079':'Quantum Eye','vocals_heavy_metal_080':'Thorn Queen','vocals_heavy_metal_081':'Pyre Phantom','vocals_heavy_metal_082':'Artemis Fury','vocals_heavy_metal_083':'Nyx Quake','vocals_heavy_metal_084':'Umber Prism','vocals_heavy_metal_085':'Lyra Cipher',
'vocals_funk_086':'Cassiopeia Wail','vocals_funk_087':'Obsidian Wraith','vocals_funk_088':'Astra Hunter','vocals_funk_089':'Calypso Star','vocals_funk_090':'Andromeda Hymn','vocals_funk_091':'Kira Dawn','vocals_funk_092':'Zero Fist','vocals_funk_093':'Raven Lament','vocals_funk_094':'Vesper Prophet','vocals_funk_095':'Neon Eclipse',
'vocals_blues_096':'Lyric Cobra','vocals_blues_097':'Dusk Crown','vocals_blues_098':'Glitch Nadir','vocals_blues_099':'Moss Crown','vocals_blues_100':'Feral Dusk','vocals_blues_101':'Flux Lament','vocals_blues_102':'Jolt Raven','vocals_blues_103':'Xyla Nadir',
'vocals_jazz_104':'Storm Hunter','vocals_jazz_105':'Wisp Apex','vocals_jazz_106':'Haze Whisper','vocals_jazz_107':'Jinx Requiem','vocals_jazz_108':'Fractal Serpent',
'vocals_psychedelic_109':'Omega Cinder','vocals_psychedelic_110':'Myth Nexus',
'vocals_prog_rock_111':'Lyra Dawn',
}

const results = CHARS.map(([archKey, num, hair, color, skin, mod, kit]) => {
  const numStr = String(num).padStart(3, '0')
  const id = `${archKey}_${numStr}`
  const builder = T[archKey]
  if (!builder) { console.error('Missing template for', archKey); process.exit(1) }
  const positive_prompt = builder({ hair, color, skin, mod, kit })
  return {
    id,
    positive_prompt,
    negative_prompt: NEG,
    archetype: ARCHETYPES[archKey] || archKey,
  }
})

const out = path.join(__dirname, '..', 'public', 'art_prompts.json')
fs.writeFileSync(out, JSON.stringify(results, null, 2), 'utf8')
console.log(`✓ Generated ${results.length} prompts → ${out}`)
